import { useState, useEffect } from "react";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { wsClient, WS_EVENTS } from "@/lib/ws";
import { Check, X, Archive, RotateCcw, AlertCircle, Copy } from "lucide-react";
import { cn } from "@/lib/utils";
import { LogViewer, LogEntry } from "@/components/shared/LogViewer";
import { toast } from "sonner";

export type BackupOperation = "create" | "restore" | "export" | "import";

export interface BackupStage {
  name: string;
  label: string;
  status: "pending" | "running" | "success" | "error" | "skipped";
  message?: string;
}

interface BackupLogPayload {
  operationType: string;
  pluginId: number;
  siteId: number;
  log: LogEntry;
}

interface BackupProgressDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  operation: BackupOperation;
  pluginName?: string;
  mappingId?: number;
  onComplete?: (success: boolean) => void;
}

const OPERATION_CONFIG: Record<BackupOperation, {
  title: string;
  icon: typeof Archive;
  stages: BackupStage[];
}> = {
  create: {
    title: "Creating Backup",
    icon: Archive,
    stages: [
      { name: "init", label: "Initializing", status: "pending" },
      { name: "prepare", label: "Preparing Files", status: "pending" },
      { name: "write", label: "Writing Backup", status: "pending" },
      { name: "retention", label: "Cleanup Old Backups", status: "pending" },
      { name: "complete", label: "Finalizing", status: "pending" },
    ],
  },
  restore: {
    title: "Restoring Backup",
    icon: RotateCcw,
    stages: [
      { name: "init", label: "Initializing", status: "pending" },
      { name: "locate", label: "Locating Backup", status: "pending" },
      { name: "upload", label: "Uploading to WordPress", status: "pending" },
      { name: "activate", label: "Activating Plugin", status: "pending" },
      { name: "complete", label: "Finalizing", status: "pending" },
    ],
  },
  export: {
    title: "Exporting",
    icon: Archive,
    stages: [
      { name: "init", label: "Initializing", status: "pending" },
      { name: "scan", label: "Scanning Files", status: "pending" },
      { name: "compress", label: "Compressing", status: "pending" },
      { name: "complete", label: "Finalizing", status: "pending" },
    ],
  },
  import: {
    title: "Importing",
    icon: Archive,
    stages: [
      { name: "init", label: "Initializing", status: "pending" },
      { name: "open", label: "Opening Archive", status: "pending" },
      { name: "extract", label: "Extracting Files", status: "pending" },
      { name: "complete", label: "Finalizing", status: "pending" },
    ],
  },
};

function buildErrorReport(
  operation: BackupOperation,
  pluginName: string | undefined,
  mappingId: number | undefined,
  errorMessage: string,
  stages: BackupStage[],
  logs: LogEntry[]
): string {
  const timestamp = new Date().toISOString();
  const failedStage = stages.find(s => s.status === "error");
  
  const logSection = logs.length > 0 
    ? `### Execution Logs\n\`\`\`\n${logs.map(l => `[${l.timestamp}] [${l.level.toUpperCase()}] [${l.step}] ${l.message}`).join('\n')}\n\`\`\`\n`
    : "";
  
  return `## Backup ${operation.charAt(0).toUpperCase() + operation.slice(1)} Error Report

**App:** WP Plugin Publish
**Timestamp:** ${timestamp}

### Context
- **Operation:** ${operation}
- **Plugin:** ${pluginName || "N/A"} ${mappingId ? `(Mapping ID: ${mappingId})` : ""}
- **Failed Stage:** ${failedStage?.label || "Unknown"}

### Error Message
\`\`\`
${errorMessage}
\`\`\`

### Stage Status
${stages.map(s => `- ${s.label}: ${s.status}${s.message ? ` - ${s.message}` : ""}`).join("\n")}

${logSection}
---
*Generated by WP Plugin Publish Error Reporter*`;
}

export function BackupProgressDialog({
  open,
  onOpenChange,
  operation,
  pluginName,
  mappingId,
  onComplete,
}: BackupProgressDialogProps) {
  const config = OPERATION_CONFIG[operation];
  const Icon = config.icon;
  
  const [stages, setStages] = useState<BackupStage[]>(config.stages);
  const [overallProgress, setOverallProgress] = useState(0);
  const [isComplete, setIsComplete] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [logs, setLogs] = useState<LogEntry[]>([]);

  // Reset state when dialog opens
  useEffect(() => {
    if (open) {
      setStages(config.stages.map(s => ({ ...s, status: "pending" })));
      setOverallProgress(0);
      setIsComplete(false);
      setIsSuccess(false);
      setErrorMessage(null);
      setLogs([]);
    }
  }, [open, config.stages]);

  // Listen for WebSocket log events
  useEffect(() => {
    if (!open) return;

    const unsubLog = wsClient.on(WS_EVENTS.LOG, (data: unknown) => {
      const payload = data as BackupLogPayload;
      
      // Filter for backup operation logs
      if (payload.operationType !== "backup") return;
      if (mappingId && payload.pluginId !== mappingId) return;
      
      const log = payload.log;
      if (!log) return;
      
      // Add log entry
      setLogs(prev => [...prev, log]);
      
      // Update stage status based on log step
      const step = log.step;
      setStages(prev => prev.map(s => {
        if (s.name === step) {
          let newStatus: BackupStage["status"] = "running";
          if (log.level === "error") newStatus = "error";
          else if (step === "complete" || log.message.toLowerCase().includes("complete") || log.message.toLowerCase().includes("success")) {
            newStatus = "success";
          }
          return { ...s, status: newStatus, message: log.message };
        }
        // Mark previous stages as complete if we moved past them
        const currentIdx = prev.findIndex(ps => ps.name === step);
        const stageIdx = prev.findIndex(ps => ps.name === s.name);
        if (currentIdx > stageIdx && s.status === "running") {
          return { ...s, status: "success" };
        }
        return s;
      }));
      
      // Update progress
      const completedCount = stages.filter(s => s.status === "success").length;
      setOverallProgress(Math.round((completedCount / stages.length) * 100));
      
      // Handle completion
      if (step === "complete") {
        const success = log.level !== "error";
        setIsComplete(true);
        setIsSuccess(success);
        setOverallProgress(100);
        if (!success) {
          setErrorMessage(log.message);
        }
        onComplete?.(success);
      }
      
      // Handle errors
      if (log.level === "error") {
        setErrorMessage(log.message);
      }
    });

    return () => {
      unsubLog();
    };
  }, [open, mappingId, stages, onComplete]);

  const getStageIcon = (stage: BackupStage) => {
    switch (stage.status) {
      case "success":
        return <Check className="h-4 w-4 text-primary" />;
      case "error":
        return <X className="h-4 w-4 text-destructive" />;
      case "running":
        return <div className="h-4 w-4 border-2 border-primary border-t-transparent rounded-full animate-spin" />;
      default:
        return <div className="h-4 w-4 rounded-full border-2 border-muted-foreground/30" />;
    }
  };

  const activeStageCount = stages.filter(s => s.status === "success" || s.status === "running").length;
  const totalStages = stages.length;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg max-h-[90vh] flex flex-col overflow-hidden">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Icon className="h-5 w-5 text-primary" />
            {isComplete ? (isSuccess ? `${config.title} Complete` : `${config.title} Failed`) : config.title}
          </DialogTitle>
          <DialogDescription>
            {pluginName ? (
              <>Backup operation for <strong>{pluginName}</strong></>
            ) : (
              <>Processing backup operation...</>
            )}
          </DialogDescription>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto space-y-4 py-4">
          {/* Overall Progress */}
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span className="text-muted-foreground">
                Stage {Math.min(activeStageCount + 1, totalStages)} of {totalStages}
              </span>
              <span className="font-medium">{Math.round(overallProgress)}%</span>
            </div>
            <Progress value={overallProgress} className="h-2" />
          </div>

          {/* Stage List */}
          <div className="space-y-2">
            {stages.map((stage) => (
              <div
                key={stage.name}
                className={cn(
                  "flex items-center gap-3 p-3 rounded-lg border transition-colors",
                  stage.status === "running" && "border-primary bg-primary/5",
                  stage.status === "success" && "border-primary/30 bg-primary/5",
                  stage.status === "error" && "border-destructive bg-destructive/5",
                  stage.status === "pending" && "border-border opacity-60"
                )}
              >
                {getStageIcon(stage)}
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium">{stage.label}</p>
                  {stage.message && (
                    <p className="text-xs text-muted-foreground truncate">
                      {stage.message}
                    </p>
                  )}
                </div>
                {stage.status === "success" && (
                  <Badge variant="outline" className="text-xs text-primary border-primary/30">
                    Done
                  </Badge>
                )}
                {stage.status === "error" && (
                  <Badge variant="outline" className="text-xs text-destructive border-destructive/30">
                    Failed
                  </Badge>
                )}
              </div>
            ))}
          </div>

          {/* Live Logs using LogViewer */}
          <LogViewer
            logs={logs}
            title="Operation Logs"
            height="h-32"
            emptyMessage="Waiting for operation to start..."
          />

          {/* Success Message */}
          {isComplete && isSuccess && (
            <div className="rounded-lg border border-primary/30 bg-primary/5 p-4">
              <div className="flex items-center gap-2">
                <Check className="h-5 w-5 text-primary" />
                <span className="font-medium">
                  {operation === "create" && "Backup created successfully"}
                  {operation === "restore" && "Backup restored successfully"}
                  {operation === "export" && "Export completed successfully"}
                  {operation === "import" && "Import completed successfully"}
                </span>
              </div>
            </div>
          )}

          {/* Error Message */}
          {isComplete && !isSuccess && errorMessage && (
            <div className="rounded-lg border border-destructive/30 bg-destructive/5 p-4 space-y-3">
              <div className="flex items-start gap-2">
                <AlertCircle className="h-5 w-5 text-destructive mt-0.5 flex-shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="font-medium text-destructive">Operation Failed</p>
                  <p className="text-sm text-muted-foreground mt-1 break-words">{errorMessage}</p>
                </div>
              </div>
              
              <div className="flex gap-2 pt-2 border-t border-destructive/20">
                <Button
                  variant="outline"
                  size="sm"
                  className="text-xs"
                  onClick={() => {
                    const report = buildErrorReport(operation, pluginName, mappingId, errorMessage, stages, logs);
                    navigator.clipboard.writeText(report);
                    toast.success("Error report copied to clipboard");
                  }}
                >
                  <Copy className="h-3 w-3 mr-1" />
                  Copy Error Report
                </Button>
              </div>
            </div>
          )}
        </div>

        <DialogFooter>
          <Button
            variant={isComplete ? "default" : "outline"}
            onClick={() => onOpenChange(false)}
          >
            {isComplete ? "Done" : "Close"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
