<?php
/**
 * Backward-Compatibility Aliases — RISEUP_ Prefixed Constants
 *
 * Maps legacy RISEUP_* prefixed constant names to their unprefixed
 * equivalents defined in constants.php. This file exists to prevent
 * undefined constant errors while consumers are migrated.
 *
 * DELETE THIS FILE once all RISEUP_* references are replaced.
 *
 * @package RiseupAsiaUploader
 * @since   1.57.0
 * @deprecated Remove after Phase 2 consumer migration is complete.
 */

if (!defined('ABSPATH')) {
    exit;
}

// =============================================================================
// PLUGIN IDENTITY
// =============================================================================

if (!defined('RISEUP_VERSION')) { define('RISEUP_VERSION', PLUGIN_VERSION); }
if (!defined('RISEUP_SLUG'))    { define('RISEUP_SLUG', PLUGIN_SLUG); }
if (!defined('RISEUP_NAME'))    { define('RISEUP_NAME', PLUGIN_NAME); }

// =============================================================================
// PATHS
// =============================================================================

if (!defined('RISEUP_UPLOADS_SUBDIR'))    { define('RISEUP_UPLOADS_SUBDIR', UPLOADS_SUBDIR); }
if (!defined('RISEUP_LOGS_SUBDIR'))       { define('RISEUP_LOGS_SUBDIR', LOGS_SUBDIR); }
if (!defined('RISEUP_LOG_FILENAME'))      { define('RISEUP_LOG_FILENAME', LOG_FILENAME); }
if (!defined('RISEUP_ERROR_LOG_FILENAME')){ define('RISEUP_ERROR_LOG_FILENAME', ERROR_LOG_FILENAME); }
if (!defined('RISEUP_STACKTRACE_FILENAME')){ define('RISEUP_STACKTRACE_FILENAME', STACKTRACE_FILENAME); }
if (!defined('RISEUP_DB_FILENAME'))       { define('RISEUP_DB_FILENAME', DB_FILENAME); }
if (!defined('RISEUP_TEMP_SUBDIR'))       { define('RISEUP_TEMP_SUBDIR', TEMP_SUBDIR); }
if (!defined('RISEUP_SNAPSHOTS_SUBDIR'))  { define('RISEUP_SNAPSHOTS_SUBDIR', SNAPSHOTS_SUBDIR); }

// =============================================================================
// REST API CONFIGURATION
// =============================================================================

if (!defined('RISEUP_API_NAMESPACE'))      { define('RISEUP_API_NAMESPACE', API_NAMESPACE); }
if (!defined('RISEUP_API_VERSION'))        { define('RISEUP_API_VERSION', API_VERSION); }
if (!defined('RISEUP_API_FULL_NAMESPACE')) { define('RISEUP_API_FULL_NAMESPACE', API_FULL_NAMESPACE); }
if (!defined('RISEUP_LEGACY_NAMESPACE'))   { define('RISEUP_LEGACY_NAMESPACE', LEGACY_NAMESPACE); }

// =============================================================================
// REST API ENDPOINTS
// =============================================================================

if (!defined('RISEUP_ENDPOINT_STATUS'))       { define('RISEUP_ENDPOINT_STATUS', ENDPOINT_STATUS); }
if (!defined('RISEUP_ENDPOINT_UPLOAD'))       { define('RISEUP_ENDPOINT_UPLOAD', ENDPOINT_UPLOAD); }
if (!defined('RISEUP_ENDPOINT_PLUGINS'))      { define('RISEUP_ENDPOINT_PLUGINS', ENDPOINT_PLUGINS); }
if (!defined('RISEUP_ENDPOINT_EXPORT_SELF'))  { define('RISEUP_ENDPOINT_EXPORT_SELF', ENDPOINT_EXPORT_SELF); }
if (!defined('RISEUP_ENDPOINT_POSTS'))        { define('RISEUP_ENDPOINT_POSTS', ENDPOINT_POSTS); }
if (!defined('RISEUP_ENDPOINT_CATEGORIES'))   { define('RISEUP_ENDPOINT_CATEGORIES', ENDPOINT_CATEGORIES); }
if (!defined('RISEUP_ENDPOINT_LOGS'))         { define('RISEUP_ENDPOINT_LOGS', ENDPOINT_LOGS); }
if (!defined('RISEUP_ENDPOINT_LOGS_STATS'))   { define('RISEUP_ENDPOINT_LOGS_STATS', ENDPOINT_LOGS_STATS); }
if (!defined('RISEUP_ENDPOINT_PLUGIN_FILES')) { define('RISEUP_ENDPOINT_PLUGIN_FILES', ENDPOINT_PLUGIN_FILES); }
if (!defined('RISEUP_ENDPOINT_PLUGIN_FILE'))  { define('RISEUP_ENDPOINT_PLUGIN_FILE', ENDPOINT_PLUGIN_FILE); }
if (!defined('RISEUP_ENDPOINT_PLUGIN_ENABLE')){ define('RISEUP_ENDPOINT_PLUGIN_ENABLE', ENDPOINT_PLUGIN_ENABLE); }
if (!defined('RISEUP_ENDPOINT_PLUGIN_DISABLE')){ define('RISEUP_ENDPOINT_PLUGIN_DISABLE', ENDPOINT_PLUGIN_DISABLE); }
if (!defined('RISEUP_ENDPOINT_PLUGIN_DELETE')){ define('RISEUP_ENDPOINT_PLUGIN_DELETE', ENDPOINT_PLUGIN_DELETE); }
if (!defined('RISEUP_ENDPOINT_PLUGIN_EXISTS')){ define('RISEUP_ENDPOINT_PLUGIN_EXISTS', ENDPOINT_PLUGIN_EXISTS); }
if (!defined('RISEUP_ENDPOINT_PLUGIN_EXPORT')){ define('RISEUP_ENDPOINT_PLUGIN_EXPORT', ENDPOINT_PLUGIN_EXPORT); }
if (!defined('RISEUP_ENDPOINT_OPENAPI'))      { define('RISEUP_ENDPOINT_OPENAPI', ENDPOINT_OPENAPI); }
if (!defined('RISEUP_ENDPOINT_OPCACHE_RESET')){ define('RISEUP_ENDPOINT_OPCACHE_RESET', ENDPOINT_OPCACHE_RESET); }
if (!defined('RISEUP_ENDPOINT_SYNC_MANIFEST')){ define('RISEUP_ENDPOINT_SYNC_MANIFEST', ENDPOINT_SYNC_MANIFEST); }
if (!defined('RISEUP_ENDPOINT_SYNC'))         { define('RISEUP_ENDPOINT_SYNC', ENDPOINT_SYNC); }
if (!defined('RISEUP_ENDPOINT_ERROR_LOGS'))   { define('RISEUP_ENDPOINT_ERROR_LOGS', ENDPOINT_ERROR_LOGS); }
if (!defined('RISEUP_ENDPOINT_ERROR_SESSIONS')){ define('RISEUP_ENDPOINT_ERROR_SESSIONS', ENDPOINT_ERROR_SESSIONS); }

// Agent endpoints
if (!defined('RISEUP_ENDPOINT_AGENTS'))       { define('RISEUP_ENDPOINT_AGENTS', ENDPOINT_AGENTS); }
if (!defined('RISEUP_ENDPOINT_AGENTS_LIST'))  { define('RISEUP_ENDPOINT_AGENTS_LIST', ENDPOINT_AGENTS_LIST); }
if (!defined('RISEUP_ENDPOINT_AGENTS_ADD'))   { define('RISEUP_ENDPOINT_AGENTS_ADD', ENDPOINT_AGENTS_ADD); }
if (!defined('RISEUP_ENDPOINT_AGENTS_REMOVE')){ define('RISEUP_ENDPOINT_AGENTS_REMOVE', ENDPOINT_AGENTS_REMOVE); }
if (!defined('RISEUP_ENDPOINT_AGENTS_TEST'))  { define('RISEUP_ENDPOINT_AGENTS_TEST', ENDPOINT_AGENTS_TEST); }
if (!defined('RISEUP_ENDPOINT_AGENTS_SYNC'))  { define('RISEUP_ENDPOINT_AGENTS_SYNC', ENDPOINT_AGENTS_SYNC); }
if (!defined('RISEUP_ENDPOINT_AGENTS_PLUGINS')){ define('RISEUP_ENDPOINT_AGENTS_PLUGINS', ENDPOINT_AGENTS_PLUGINS); }

// Snapshot endpoints
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_LIST'))     { define('RISEUP_ENDPOINT_SNAPSHOT_LIST', ENDPOINT_SNAPSHOT_LIST); }
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_SCHEDULE')) { define('RISEUP_ENDPOINT_SNAPSHOT_SCHEDULE', ENDPOINT_SNAPSHOT_SCHEDULE); }
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_INFO'))     { define('RISEUP_ENDPOINT_SNAPSHOT_INFO', ENDPOINT_SNAPSHOT_INFO); }
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_DELETE'))   { define('RISEUP_ENDPOINT_SNAPSHOT_DELETE', ENDPOINT_SNAPSHOT_DELETE); }
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_RESTORE'))  { define('RISEUP_ENDPOINT_SNAPSHOT_RESTORE', ENDPOINT_SNAPSHOT_RESTORE); }
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_EXPORT'))   { define('RISEUP_ENDPOINT_SNAPSHOT_EXPORT', ENDPOINT_SNAPSHOT_EXPORT); }
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_IMPORT'))   { define('RISEUP_ENDPOINT_SNAPSHOT_IMPORT', ENDPOINT_SNAPSHOT_IMPORT); }
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_SETTINGS')) { define('RISEUP_ENDPOINT_SNAPSHOT_SETTINGS', ENDPOINT_SNAPSHOT_SETTINGS); }
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_PROVIDERS')){ define('RISEUP_ENDPOINT_SNAPSHOT_PROVIDERS', ENDPOINT_SNAPSHOT_PROVIDERS); }
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_TABLES'))   { define('RISEUP_ENDPOINT_SNAPSHOT_TABLES', ENDPOINT_SNAPSHOT_TABLES); }
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_FULL_BACKUP')){ define('RISEUP_ENDPOINT_SNAPSHOT_FULL_BACKUP', ENDPOINT_SNAPSHOT_FULL_BACKUP); }
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_INCREMENTAL')){ define('RISEUP_ENDPOINT_SNAPSHOT_INCREMENTAL', ENDPOINT_SNAPSHOT_INCREMENTAL); }
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_CLEANUP'))  { define('RISEUP_ENDPOINT_SNAPSHOT_CLEANUP', ENDPOINT_SNAPSHOT_CLEANUP); }
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_PROGRESS')) { define('RISEUP_ENDPOINT_SNAPSHOT_PROGRESS', ENDPOINT_SNAPSHOT_PROGRESS); }
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_DOWNLOAD')) { define('RISEUP_ENDPOINT_SNAPSHOT_DOWNLOAD', ENDPOINT_SNAPSHOT_DOWNLOAD); }
if (!defined('RISEUP_ENDPOINT_SNAPSHOT_DOWNLOAD_FILE')){ define('RISEUP_ENDPOINT_SNAPSHOT_DOWNLOAD_FILE', ENDPOINT_SNAPSHOT_DOWNLOAD_FILE); }

// Media endpoint
if (!defined('RISEUP_ENDPOINT_MEDIA')) {
    if (defined('ENDPOINT_MEDIA')) { define('RISEUP_ENDPOINT_MEDIA', ENDPOINT_MEDIA); }
}

// =============================================================================
// HTTP STATUS CODES
// =============================================================================

if (!defined('RISEUP_HTTP_OK'))           { define('RISEUP_HTTP_OK', HTTP_OK); }
if (!defined('RISEUP_HTTP_CREATED'))      { define('RISEUP_HTTP_CREATED', HTTP_CREATED); }
if (!defined('RISEUP_HTTP_BAD_REQUEST'))  { define('RISEUP_HTTP_BAD_REQUEST', HTTP_BAD_REQUEST); }
if (!defined('RISEUP_HTTP_UNAUTHORIZED')) { define('RISEUP_HTTP_UNAUTHORIZED', HTTP_UNAUTHORIZED); }
if (!defined('RISEUP_HTTP_FORBIDDEN'))    { define('RISEUP_HTTP_FORBIDDEN', HTTP_FORBIDDEN); }
if (!defined('RISEUP_HTTP_NOT_FOUND'))    { define('RISEUP_HTTP_NOT_FOUND', HTTP_NOT_FOUND); }
if (!defined('RISEUP_HTTP_SERVER_ERROR')) { define('RISEUP_HTTP_SERVER_ERROR', HTTP_SERVER_ERROR); }

// =============================================================================
// DATABASE
// =============================================================================

if (!defined('RISEUP_TABLE_TRANSACTIONS'))     { define('RISEUP_TABLE_TRANSACTIONS', TABLE_TRANSACTIONS); }
if (!defined('RISEUP_TABLE_AGENT_SITES'))      { define('RISEUP_TABLE_AGENT_SITES', TABLE_AGENT_SITES); }
if (!defined('RISEUP_TABLE_AGENT_ACTIONS'))    { define('RISEUP_TABLE_AGENT_ACTIONS', TABLE_AGENT_ACTIONS); }
if (!defined('RISEUP_TABLE_SNAPSHOTS'))        { define('RISEUP_TABLE_SNAPSHOTS', TABLE_SNAPSHOTS); }
if (!defined('RISEUP_TABLE_SNAPSHOT_PROGRESS')){ define('RISEUP_TABLE_SNAPSHOT_PROGRESS', TABLE_SNAPSHOT_PROGRESS); }
if (!defined('RISEUP_TABLE_SNAPSHOT_JOBS'))    { define('RISEUP_TABLE_SNAPSHOT_JOBS', TABLE_SNAPSHOT_JOBS); }
if (!defined('RISEUP_TABLE_SNAPSHOT_SETTINGS')){ define('RISEUP_TABLE_SNAPSHOT_SETTINGS', TABLE_SNAPSHOT_SETTINGS); }
if (!defined('RISEUP_TABLE_SNAPSHOT_EXPORTS')) { define('RISEUP_TABLE_SNAPSHOT_EXPORTS', TABLE_SNAPSHOT_EXPORTS); }
if (!defined('RISEUP_TABLE_FILE_CACHE'))       { define('RISEUP_TABLE_FILE_CACHE', TABLE_FILE_CACHE); }
if (!defined('RISEUP_DB_WAL_MODE'))            { define('RISEUP_DB_WAL_MODE', DB_WAL_MODE); }

// =============================================================================
// ACTIONS
// =============================================================================

if (!defined('RISEUP_ACTION_UPLOAD'))          { define('RISEUP_ACTION_UPLOAD', ACTION_UPLOAD); }
if (!defined('RISEUP_ACTION_UPLOAD_ACTIVE'))   { define('RISEUP_ACTION_UPLOAD_ACTIVE', ACTION_UPLOAD_ACTIVE); }
if (!defined('RISEUP_ACTION_ENABLE'))          { define('RISEUP_ACTION_ENABLE', ACTION_ENABLE); }
if (!defined('RISEUP_ACTION_DISABLE'))         { define('RISEUP_ACTION_DISABLE', ACTION_DISABLE); }
if (!defined('RISEUP_ACTION_DELETE'))          { define('RISEUP_ACTION_DELETE', ACTION_DELETE); }
if (!defined('RISEUP_ACTION_FILE_REPLACE'))    { define('RISEUP_ACTION_FILE_REPLACE', ACTION_FILE_REPLACE); }
if (!defined('RISEUP_ACTION_FILE_DELETE'))     { define('RISEUP_ACTION_FILE_DELETE', ACTION_FILE_DELETE); }
if (!defined('RISEUP_ACTION_SYNC'))            { define('RISEUP_ACTION_SYNC', ACTION_SYNC); }
if (!defined('RISEUP_ACTION_SYNC_DELETE'))     { define('RISEUP_ACTION_SYNC_DELETE', ACTION_SYNC_DELETE); }
if (!defined('RISEUP_ACTION_POST_CREATE'))     { define('RISEUP_ACTION_POST_CREATE', ACTION_POST_CREATE); }
if (!defined('RISEUP_ACTION_POST_UPDATE'))     { define('RISEUP_ACTION_POST_UPDATE', ACTION_POST_UPDATE); }
if (!defined('RISEUP_ACTION_CATEGORY_CREATE')) { define('RISEUP_ACTION_CATEGORY_CREATE', ACTION_CATEGORY_CREATE); }
if (!defined('RISEUP_ACTION_MEDIA_UPLOAD'))    { define('RISEUP_ACTION_MEDIA_UPLOAD', ACTION_MEDIA_UPLOAD); }
if (!defined('RISEUP_ACTION_AUTH_FAILED'))     { define('RISEUP_ACTION_AUTH_FAILED', ACTION_AUTH_FAILED); }
if (!defined('RISEUP_ACTION_EXPORT_SELF'))     { define('RISEUP_ACTION_EXPORT_SELF', ACTION_EXPORT_SELF); }
if (!defined('RISEUP_ACTION_EXPORT_PLUGIN'))   { define('RISEUP_ACTION_EXPORT_PLUGIN', ACTION_EXPORT_PLUGIN); }
if (!defined('RISEUP_ACTION_UPLOAD_INITIATED')){ define('RISEUP_ACTION_UPLOAD_INITIATED', ACTION_UPLOAD_INITIATED); }
if (!defined('RISEUP_ACTION_UPDATE_CHECK'))    { define('RISEUP_ACTION_UPDATE_CHECK', ACTION_UPDATE_CHECK); }
if (!defined('RISEUP_ACTION_UPDATE_RESOLVE'))  { define('RISEUP_ACTION_UPDATE_RESOLVE', ACTION_UPDATE_RESOLVE); }
if (!defined('RISEUP_ACTION_UPDATE_DOWNLOAD')) { define('RISEUP_ACTION_UPDATE_DOWNLOAD', ACTION_UPDATE_DOWNLOAD); }
if (!defined('RISEUP_ACTION_UPDATE_INSTALL'))  { define('RISEUP_ACTION_UPDATE_INSTALL', ACTION_UPDATE_INSTALL); }
if (!defined('RISEUP_ACTION_AGENT_ADD'))       { define('RISEUP_ACTION_AGENT_ADD', ACTION_AGENT_ADD); }
if (!defined('RISEUP_ACTION_AGENT_REMOVE'))    { define('RISEUP_ACTION_AGENT_REMOVE', ACTION_AGENT_REMOVE); }
if (!defined('RISEUP_ACTION_AGENT_TEST'))      { define('RISEUP_ACTION_AGENT_TEST', ACTION_AGENT_TEST); }
if (!defined('RISEUP_ACTION_AGENT_SYNC'))      { define('RISEUP_ACTION_AGENT_SYNC', ACTION_AGENT_SYNC); }
if (!defined('RISEUP_ACTION_AGENT_PLUGIN_ENABLE'))  { define('RISEUP_ACTION_AGENT_PLUGIN_ENABLE', ACTION_AGENT_PLUGIN_ENABLE); }
if (!defined('RISEUP_ACTION_AGENT_PLUGIN_DISABLE')) { define('RISEUP_ACTION_AGENT_PLUGIN_DISABLE', ACTION_AGENT_PLUGIN_DISABLE); }
if (!defined('RISEUP_ACTION_AGENT_PLUGIN_DELETE'))  { define('RISEUP_ACTION_AGENT_PLUGIN_DELETE', ACTION_AGENT_PLUGIN_DELETE); }
if (!defined('RISEUP_ACTION_AGENT_PLUGIN_UPDATE'))  { define('RISEUP_ACTION_AGENT_PLUGIN_UPDATE', ACTION_AGENT_PLUGIN_UPDATE); }
if (!defined('RISEUP_ACTION_SNAPSHOT_CREATE'))  { define('RISEUP_ACTION_SNAPSHOT_CREATE', ACTION_SNAPSHOT_CREATE); }
if (!defined('RISEUP_ACTION_SNAPSHOT_RESTORE')){ define('RISEUP_ACTION_SNAPSHOT_RESTORE', ACTION_SNAPSHOT_RESTORE); }
if (!defined('RISEUP_ACTION_SNAPSHOT_DELETE')) { define('RISEUP_ACTION_SNAPSHOT_DELETE', ACTION_SNAPSHOT_DELETE); }
if (!defined('RISEUP_ACTION_SNAPSHOT_EXPORT')) { define('RISEUP_ACTION_SNAPSHOT_EXPORT', ACTION_SNAPSHOT_EXPORT); }
if (!defined('RISEUP_ACTION_SNAPSHOT_IMPORT')) { define('RISEUP_ACTION_SNAPSHOT_IMPORT', ACTION_SNAPSHOT_IMPORT); }
if (!defined('RISEUP_ACTION_SNAPSHOT_CLEANUP')){ define('RISEUP_ACTION_SNAPSHOT_CLEANUP', ACTION_SNAPSHOT_CLEANUP); }
if (!defined('RISEUP_ACTION_SNAPSHOT_FULL_BACKUP'))   { define('RISEUP_ACTION_SNAPSHOT_FULL_BACKUP', ACTION_SNAPSHOT_FULL_BACKUP); }
if (!defined('RISEUP_ACTION_SNAPSHOT_INCREMENTAL'))   { define('RISEUP_ACTION_SNAPSHOT_INCREMENTAL', ACTION_SNAPSHOT_INCREMENTAL); }
if (!defined('RISEUP_ACTION_SNAPSHOT_RESTORE_PERTABLE')){ define('RISEUP_ACTION_SNAPSHOT_RESTORE_PERTABLE', ACTION_SNAPSHOT_RESTORE_PERTABLE); }
if (!defined('RISEUP_ACTION_SNAPSHOT_IMPORT_PERTABLE')) { define('RISEUP_ACTION_SNAPSHOT_IMPORT_PERTABLE', ACTION_SNAPSHOT_IMPORT_PERTABLE); }
if (!defined('RISEUP_ACTION_SNAPSHOT_ZIP_BUILD'))    { define('RISEUP_ACTION_SNAPSHOT_ZIP_BUILD', ACTION_SNAPSHOT_ZIP_BUILD); }
if (!defined('RISEUP_ACTION_SNAPSHOT_ZIP_EXPIRE'))   { define('RISEUP_ACTION_SNAPSHOT_ZIP_EXPIRE', ACTION_SNAPSHOT_ZIP_EXPIRE); }
if (!defined('RISEUP_ACTION_SNAPSHOT_ZIP_DOWNLOAD')) { define('RISEUP_ACTION_SNAPSHOT_ZIP_DOWNLOAD', ACTION_SNAPSHOT_ZIP_DOWNLOAD); }

// =============================================================================
// STATUS VALUES
// =============================================================================

if (!defined('RISEUP_STATUS_SUCCESS')) { define('RISEUP_STATUS_SUCCESS', STATUS_SUCCESS); }
if (!defined('RISEUP_STATUS_FAILED'))  { define('RISEUP_STATUS_FAILED', STATUS_FAILED); }

// =============================================================================
// POST STATUS
// =============================================================================

if (!defined('RISEUP_POST_STATUS_PUBLISH')) { define('RISEUP_POST_STATUS_PUBLISH', POST_STATUS_PUBLISH); }
if (!defined('RISEUP_POST_STATUS_DRAFT'))   { define('RISEUP_POST_STATUS_DRAFT', POST_STATUS_DRAFT); }
if (!defined('RISEUP_POST_STATUS_PENDING')) { define('RISEUP_POST_STATUS_PENDING', POST_STATUS_PENDING); }

// =============================================================================
// RESPONSE MESSAGES
// =============================================================================

if (!defined('RISEUP_MSG_SUCCESS'))              { define('RISEUP_MSG_SUCCESS', MSG_SUCCESS); }
if (!defined('RISEUP_MSG_UNAUTHORIZED'))         { define('RISEUP_MSG_UNAUTHORIZED', MSG_UNAUTHORIZED); }
if (!defined('RISEUP_MSG_FORBIDDEN'))            { define('RISEUP_MSG_FORBIDDEN', MSG_FORBIDDEN); }
if (!defined('RISEUP_MSG_INVALID_REQUEST'))      { define('RISEUP_MSG_INVALID_REQUEST', MSG_INVALID_REQUEST); }
if (!defined('RISEUP_MSG_PLUGIN_NOT_FOUND'))     { define('RISEUP_MSG_PLUGIN_NOT_FOUND', MSG_PLUGIN_NOT_FOUND); }
if (!defined('RISEUP_MSG_UPLOAD_FAILED'))        { define('RISEUP_MSG_UPLOAD_FAILED', MSG_UPLOAD_FAILED); }
if (!defined('RISEUP_MSG_ACTIVATION_FAILED'))    { define('RISEUP_MSG_ACTIVATION_FAILED', MSG_ACTIVATION_FAILED); }
if (!defined('RISEUP_MSG_DEACTIVATION_FAILED'))  { define('RISEUP_MSG_DEACTIVATION_FAILED', MSG_DEACTIVATION_FAILED); }
if (!defined('RISEUP_MSG_DELETE_FAILED'))        { define('RISEUP_MSG_DELETE_FAILED', MSG_DELETE_FAILED); }
if (!defined('RISEUP_MSG_POST_CREATE_FAILED'))   { define('RISEUP_MSG_POST_CREATE_FAILED', MSG_POST_CREATE_FAILED); }
if (!defined('RISEUP_MSG_POST_UPDATE_FAILED'))   { define('RISEUP_MSG_POST_UPDATE_FAILED', MSG_POST_UPDATE_FAILED); }
if (!defined('RISEUP_MSG_CATEGORY_CREATE_FAILED')){ define('RISEUP_MSG_CATEGORY_CREATE_FAILED', MSG_CATEGORY_CREATE_FAILED); }
if (!defined('RISEUP_MSG_MEDIA_UPLOAD_FAILED'))  { define('RISEUP_MSG_MEDIA_UPLOAD_FAILED', MSG_MEDIA_UPLOAD_FAILED); }
if (!defined('RISEUP_MSG_DB_ERROR'))             { define('RISEUP_MSG_DB_ERROR', MSG_DB_ERROR); }
if (!defined('RISEUP_MSG_FILE_IGNORED'))         { define('RISEUP_MSG_FILE_IGNORED', MSG_FILE_IGNORED); }

// =============================================================================
// CAPABILITIES
// =============================================================================

if (!defined('RISEUP_CAP_MANAGE_PLUGINS')) { define('RISEUP_CAP_MANAGE_PLUGINS', CAP_MANAGE_PLUGINS); }
if (!defined('RISEUP_CAP_MANAGE_POSTS'))   { define('RISEUP_CAP_MANAGE_POSTS', CAP_MANAGE_POSTS); }
if (!defined('RISEUP_CAP_UPLOAD_MEDIA'))   { define('RISEUP_CAP_UPLOAD_MEDIA', CAP_UPLOAD_MEDIA); }
if (!defined('RISEUP_CAP_VIEW_LOGS'))      { define('RISEUP_CAP_VIEW_LOGS', CAP_VIEW_LOGS); }

// =============================================================================
// PAGINATION
// =============================================================================

if (!defined('RISEUP_DEFAULT_LIMIT')) { define('RISEUP_DEFAULT_LIMIT', DEFAULT_LIMIT); }
if (!defined('RISEUP_MAX_LIMIT'))     { define('RISEUP_MAX_LIMIT', MAX_LIMIT); }

// =============================================================================
// LOG LEVELS
// =============================================================================

if (!defined('RISEUP_LOG_LEVEL_DEBUG')) { define('RISEUP_LOG_LEVEL_DEBUG', LOG_LEVEL_DEBUG); }
if (!defined('RISEUP_LOG_LEVEL_INFO'))  { define('RISEUP_LOG_LEVEL_INFO', LOG_LEVEL_INFO); }
if (!defined('RISEUP_LOG_LEVEL_WARN'))  { define('RISEUP_LOG_LEVEL_WARN', LOG_LEVEL_WARN); }
if (!defined('RISEUP_LOG_LEVEL_ERROR')) { define('RISEUP_LOG_LEVEL_ERROR', LOG_LEVEL_ERROR); }
if (!defined('RISEUP_LOG_PREFIX'))      { define('RISEUP_LOG_PREFIX', LOG_PREFIX); }

// =============================================================================
// IGNORE FILE
// =============================================================================

if (!defined('RISEUP_IGNORE_FILENAME')) { define('RISEUP_IGNORE_FILENAME', IGNORE_FILENAME); }

// =============================================================================
// AUTO-UPDATE
// =============================================================================

if (!defined('RISEUP_UPDATE_CACHE_DAYS_DEFAULT')) { define('RISEUP_UPDATE_CACHE_DAYS_DEFAULT', UPDATE_CACHE_DAYS_DEFAULT); }
if (!defined('RISEUP_UPDATE_MAX_REDIRECTS'))      { define('RISEUP_UPDATE_MAX_REDIRECTS', UPDATE_MAX_REDIRECTS); }

// =============================================================================
// AGENT STATUS
// =============================================================================

if (!defined('RISEUP_AGENT_STATUS_PENDING'))   { define('RISEUP_AGENT_STATUS_PENDING', AGENT_STATUS_PENDING); }
if (!defined('RISEUP_AGENT_STATUS_CONNECTED')) { define('RISEUP_AGENT_STATUS_CONNECTED', AGENT_STATUS_CONNECTED); }
if (!defined('RISEUP_AGENT_STATUS_ERROR'))     { define('RISEUP_AGENT_STATUS_ERROR', AGENT_STATUS_ERROR); }

// =============================================================================
// TRIGGERED_BY VALUES
// =============================================================================

if (!defined('RISEUP_TRIGGERED_BY_API'))       { define('RISEUP_TRIGGERED_BY_API', TRIGGERED_BY_API); }
if (!defined('RISEUP_TRIGGERED_BY_DASHBOARD')) { define('RISEUP_TRIGGERED_BY_DASHBOARD', TRIGGERED_BY_DASHBOARD); }
if (!defined('RISEUP_TRIGGERED_BY_AGENT'))     { define('RISEUP_TRIGGERED_BY_AGENT', TRIGGERED_BY_AGENT); }
if (!defined('RISEUP_TRIGGERED_BY_CRON'))      { define('RISEUP_TRIGGERED_BY_CRON', TRIGGERED_BY_CRON); }
if (!defined('RISEUP_TRIGGERED_BY_CLI'))       { define('RISEUP_TRIGGERED_BY_CLI', TRIGGERED_BY_CLI); }

// =============================================================================
// SYNC
// =============================================================================

if (!defined('RISEUP_SYNC_ACTION_REPLACE')) { define('RISEUP_SYNC_ACTION_REPLACE', SYNC_ACTION_REPLACE); }
if (!defined('RISEUP_SYNC_ACTION_DELETE'))  { define('RISEUP_SYNC_ACTION_DELETE', SYNC_ACTION_DELETE); }

// =============================================================================
// SNAPSHOT SYSTEM
// =============================================================================

// Providers
if (!defined('RISEUP_SNAPSHOT_PROVIDER_WP_RESET')) { define('RISEUP_SNAPSHOT_PROVIDER_WP_RESET', SNAPSHOT_PROVIDER_WP_RESET); }
if (!defined('RISEUP_SNAPSHOT_PROVIDER_UPDRAFT'))   { define('RISEUP_SNAPSHOT_PROVIDER_UPDRAFT', SNAPSHOT_PROVIDER_UPDRAFT); }
if (!defined('RISEUP_SNAPSHOT_PROVIDER_NATIVE'))    { define('RISEUP_SNAPSHOT_PROVIDER_NATIVE', SNAPSHOT_PROVIDER_NATIVE); }
if (!defined('RISEUP_SNAPSHOT_PROVIDER_AUTO'))      { define('RISEUP_SNAPSHOT_PROVIDER_AUTO', SNAPSHOT_PROVIDER_AUTO); }

// Status
if (!defined('RISEUP_SNAPSHOT_STATUS_PENDING'))   { define('RISEUP_SNAPSHOT_STATUS_PENDING', SNAPSHOT_STATUS_PENDING); }
if (!defined('RISEUP_SNAPSHOT_STATUS_SCHEDULED')) { define('RISEUP_SNAPSHOT_STATUS_SCHEDULED', SNAPSHOT_STATUS_SCHEDULED); }
if (!defined('RISEUP_SNAPSHOT_STATUS_RUNNING'))   { define('RISEUP_SNAPSHOT_STATUS_RUNNING', SNAPSHOT_STATUS_RUNNING); }
if (!defined('RISEUP_SNAPSHOT_STATUS_COMPLETE'))  { define('RISEUP_SNAPSHOT_STATUS_COMPLETE', SNAPSHOT_STATUS_COMPLETE); }
if (!defined('RISEUP_SNAPSHOT_STATUS_FAILED'))    { define('RISEUP_SNAPSHOT_STATUS_FAILED', SNAPSHOT_STATUS_FAILED); }

// Scope
if (!defined('RISEUP_SNAPSHOT_SCOPE_ALL'))       { define('RISEUP_SNAPSHOT_SCOPE_ALL', SNAPSHOT_SCOPE_ALL); }
if (!defined('RISEUP_SNAPSHOT_SCOPE_WORDPRESS')) { define('RISEUP_SNAPSHOT_SCOPE_WORDPRESS', SNAPSHOT_SCOPE_WORDPRESS); }
if (!defined('RISEUP_SNAPSHOT_SCOPE_CONTENT'))   { define('RISEUP_SNAPSHOT_SCOPE_CONTENT', SNAPSHOT_SCOPE_CONTENT); }
if (!defined('RISEUP_SNAPSHOT_SCOPE_CUSTOM'))    { define('RISEUP_SNAPSHOT_SCOPE_CUSTOM', SNAPSHOT_SCOPE_CUSTOM); }

// Frequencies
if (!defined('RISEUP_SNAPSHOT_FREQ_MANUAL'))  { define('RISEUP_SNAPSHOT_FREQ_MANUAL', SNAPSHOT_FREQ_MANUAL); }
if (!defined('RISEUP_SNAPSHOT_FREQ_DAILY'))   { define('RISEUP_SNAPSHOT_FREQ_DAILY', SNAPSHOT_FREQ_DAILY); }
if (!defined('RISEUP_SNAPSHOT_FREQ_WEEKLY'))  { define('RISEUP_SNAPSHOT_FREQ_WEEKLY', SNAPSHOT_FREQ_WEEKLY); }
if (!defined('RISEUP_SNAPSHOT_FREQ_MONTHLY')) { define('RISEUP_SNAPSHOT_FREQ_MONTHLY', SNAPSHOT_FREQ_MONTHLY); }

// Defaults
if (!defined('RISEUP_SNAPSHOT_BATCH_SIZE'))              { define('RISEUP_SNAPSHOT_BATCH_SIZE', SNAPSHOT_BATCH_SIZE); }
if (!defined('RISEUP_SNAPSHOT_MAX_SIZE_MB'))             { define('RISEUP_SNAPSHOT_MAX_SIZE_MB', SNAPSHOT_MAX_SIZE_MB); }
if (!defined('RISEUP_SNAPSHOT_RETENTION_DAYS_DEFAULT'))  { define('RISEUP_SNAPSHOT_RETENTION_DAYS_DEFAULT', SNAPSHOT_RETENTION_DAYS_DEFAULT); }
if (!defined('RISEUP_SNAPSHOT_RETENTION_COUNT_DEFAULT')) { define('RISEUP_SNAPSHOT_RETENTION_COUNT_DEFAULT', SNAPSHOT_RETENTION_COUNT_DEFAULT); }
if (!defined('RISEUP_SNAPSHOT_STUCK_HOURS'))             { define('RISEUP_SNAPSHOT_STUCK_HOURS', SNAPSHOT_STUCK_HOURS); }

// Worker pool
if (!defined('RISEUP_SNAPSHOT_WORKER_POOL_MIN'))     { define('RISEUP_SNAPSHOT_WORKER_POOL_MIN', SNAPSHOT_WORKER_POOL_MIN); }
if (!defined('RISEUP_SNAPSHOT_WORKER_POOL_MAX'))     { define('RISEUP_SNAPSHOT_WORKER_POOL_MAX', SNAPSHOT_WORKER_POOL_MAX); }
if (!defined('RISEUP_SNAPSHOT_WORKER_POOL_DEFAULT')) { define('RISEUP_SNAPSHOT_WORKER_POOL_DEFAULT', SNAPSHOT_WORKER_POOL_DEFAULT); }

// Job status
if (!defined('RISEUP_SNAPSHOT_JOB_STATUS_QUEUED'))     { define('RISEUP_SNAPSHOT_JOB_STATUS_QUEUED', SNAPSHOT_JOB_STATUS_QUEUED); }
if (!defined('RISEUP_SNAPSHOT_JOB_STATUS_PROCESSING')) { define('RISEUP_SNAPSHOT_JOB_STATUS_PROCESSING', SNAPSHOT_JOB_STATUS_PROCESSING); }
if (!defined('RISEUP_SNAPSHOT_JOB_STATUS_COMPLETE'))   { define('RISEUP_SNAPSHOT_JOB_STATUS_COMPLETE', SNAPSHOT_JOB_STATUS_COMPLETE); }
if (!defined('RISEUP_SNAPSHOT_JOB_STATUS_FAILED'))     { define('RISEUP_SNAPSHOT_JOB_STATUS_FAILED', SNAPSHOT_JOB_STATUS_FAILED); }

// Types
if (!defined('RISEUP_SNAPSHOT_TYPE_FULL'))        { define('RISEUP_SNAPSHOT_TYPE_FULL', SNAPSHOT_TYPE_FULL); }
if (!defined('RISEUP_SNAPSHOT_TYPE_INCREMENTAL')) { define('RISEUP_SNAPSHOT_TYPE_INCREMENTAL', SNAPSHOT_TYPE_INCREMENTAL); }

// Trigger sources
if (!defined('RISEUP_SNAPSHOT_TRIGGER_MANUAL')) { define('RISEUP_SNAPSHOT_TRIGGER_MANUAL', SNAPSHOT_TRIGGER_MANUAL); }
if (!defined('RISEUP_SNAPSHOT_TRIGGER_CRON'))   { define('RISEUP_SNAPSHOT_TRIGGER_CRON', SNAPSHOT_TRIGGER_CRON); }
if (!defined('RISEUP_SNAPSHOT_TRIGGER_API'))    { define('RISEUP_SNAPSHOT_TRIGGER_API', SNAPSHOT_TRIGGER_API); }

// Export status
if (!defined('RISEUP_SNAPSHOT_EXPORT_STATUS_VALID'))    { define('RISEUP_SNAPSHOT_EXPORT_STATUS_VALID', SNAPSHOT_EXPORT_STATUS_VALID); }
if (!defined('RISEUP_SNAPSHOT_EXPORT_STATUS_EXPIRED'))  { define('RISEUP_SNAPSHOT_EXPORT_STATUS_EXPIRED', SNAPSHOT_EXPORT_STATUS_EXPIRED); }
if (!defined('RISEUP_SNAPSHOT_EXPORT_STATUS_BUILDING')) { define('RISEUP_SNAPSHOT_EXPORT_STATUS_BUILDING', SNAPSHOT_EXPORT_STATUS_BUILDING); }
if (!defined('RISEUP_SNAPSHOT_EXPORTS_SUBDIR'))         { define('RISEUP_SNAPSHOT_EXPORTS_SUBDIR', SNAPSHOT_EXPORTS_SUBDIR); }

// Cron hooks
if (!defined('RISEUP_CRON_SNAPSHOT_SCHEDULED'))    { define('RISEUP_CRON_SNAPSHOT_SCHEDULED', CRON_SNAPSHOT_SCHEDULED); }
if (!defined('RISEUP_CRON_SNAPSHOT_IMMEDIATE'))    { define('RISEUP_CRON_SNAPSHOT_IMMEDIATE', CRON_SNAPSHOT_IMMEDIATE); }
if (!defined('RISEUP_CRON_SNAPSHOT_CLEANUP'))      { define('RISEUP_CRON_SNAPSHOT_CLEANUP', CRON_SNAPSHOT_CLEANUP); }
if (!defined('RISEUP_CRON_SNAPSHOT_RESTORE'))      { define('RISEUP_CRON_SNAPSHOT_RESTORE', CRON_SNAPSHOT_RESTORE); }
if (!defined('RISEUP_CRON_SNAPSHOT_INCREMENTAL'))  { define('RISEUP_CRON_SNAPSHOT_INCREMENTAL', CRON_SNAPSHOT_INCREMENTAL); }
if (!defined('RISEUP_CRON_SNAPSHOT_WORKER_BATCH')) { define('RISEUP_CRON_SNAPSHOT_WORKER_BATCH', CRON_SNAPSHOT_WORKER_BATCH); }

// Error codes
if (!defined('RISEUP_ERR_SNAPSHOT_LOCK_EXISTS'))  { define('RISEUP_ERR_SNAPSHOT_LOCK_EXISTS', ERR_SNAPSHOT_LOCK_EXISTS); }
if (!defined('RISEUP_ERR_SNAPSHOT_NOT_FOUND'))    { define('RISEUP_ERR_SNAPSHOT_NOT_FOUND', ERR_SNAPSHOT_NOT_FOUND); }
if (!defined('RISEUP_ERR_SNAPSHOT_CORRUPT'))      { define('RISEUP_ERR_SNAPSHOT_CORRUPT', ERR_SNAPSHOT_CORRUPT); }
if (!defined('RISEUP_ERR_SNAPSHOT_TOO_LARGE'))    { define('RISEUP_ERR_SNAPSHOT_TOO_LARGE', ERR_SNAPSHOT_TOO_LARGE); }
if (!defined('RISEUP_ERR_RESTORE_FAILED'))        { define('RISEUP_ERR_RESTORE_FAILED', ERR_RESTORE_FAILED); }
if (!defined('RISEUP_ERR_RESTORE_NO_CONFIRM'))    { define('RISEUP_ERR_RESTORE_NO_CONFIRM', ERR_RESTORE_NO_CONFIRM); }
if (!defined('RISEUP_ERR_PROVIDER_NOT_AVAILABLE')){ define('RISEUP_ERR_PROVIDER_NOT_AVAILABLE', ERR_PROVIDER_NOT_AVAILABLE); }
if (!defined('RISEUP_ERR_INCREMENTAL_NO_PARENT')) { define('RISEUP_ERR_INCREMENTAL_NO_PARENT', ERR_INCREMENTAL_NO_PARENT); }
if (!defined('RISEUP_ERR_EXPORT_NOT_FOUND'))      { define('RISEUP_ERR_EXPORT_NOT_FOUND', ERR_EXPORT_NOT_FOUND); }
if (!defined('RISEUP_ERR_EXPORT_BUILD_FAILED'))   { define('RISEUP_ERR_EXPORT_BUILD_FAILED', ERR_EXPORT_BUILD_FAILED); }
if (!defined('RISEUP_ERR_EXPORT_TOKEN_INVALID'))  { define('RISEUP_ERR_EXPORT_TOKEN_INVALID', ERR_EXPORT_TOKEN_INVALID); }

// Retention types
if (!defined('RISEUP_RETENTION_TYPE_DAYS'))  { define('RISEUP_RETENTION_TYPE_DAYS', RETENTION_TYPE_DAYS); }
if (!defined('RISEUP_RETENTION_TYPE_COUNT')) { define('RISEUP_RETENTION_TYPE_COUNT', RETENTION_TYPE_COUNT); }
if (!defined('RISEUP_RETENTION_TYPE_NONE'))  { define('RISEUP_RETENTION_TYPE_NONE', RETENTION_TYPE_NONE); }

// Options
if (!defined('RISEUP_OPTION_SNAPSHOT_SETTINGS')) { define('RISEUP_OPTION_SNAPSHOT_SETTINGS', OPTION_SNAPSHOT_SETTINGS); }
if (!defined('RISEUP_OPTION_LOG_RETRIEVAL'))     { define('RISEUP_OPTION_LOG_RETRIEVAL', OPTION_LOG_RETRIEVAL); }
