import { useState, useEffect, useRef } from "react";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { wsClient, WS_EVENTS } from "@/lib/ws";
import { Check, X, Upload, AlertCircle, ExternalLink, Copy, Terminal, Settings2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { useErrorStore, BackendLogEntry } from "@/stores/errorStore";
import { toast } from "sonner";

export interface PublishStage {
  name: string;
  label: string;
  status: "pending" | "running" | "success" | "error" | "skipped";
  message?: string;
  startedAt?: string;
  completedAt?: string;
}

interface PublishLogEntry {
  timestamp: string;
  level: 'debug' | 'info' | 'warn' | 'error';
  step: string;
  message: string;
  details?: Record<string, unknown>;
}

interface PublishProgressPayload {
  publishId: string;
  pluginId: number;
  siteId: number;
  stage: string;
  progress: number;
  message: string;
  status: string;
  log?: PublishLogEntry;
}

interface PublishCompletePayload {
  publishId: string;
  pluginId: number;
  siteId: number;
  success: boolean;
  filesUpdated?: number;
  error?: string;
  stages: PublishStage[];
  logs?: PublishLogEntry[];
  backendStackTrace?: string;
}

interface PublishProgressDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  pluginName: string;
  siteName: string;
  siteUrl?: string;
  pluginId: number;
  siteId: number;
  onComplete?: (success: boolean) => void;
}

// Build a copyable error report for the publish failure
function buildErrorReport(
  pluginName: string,
  siteName: string,
  pluginId: number,
  siteId: number,
  errorMessage: string,
  stages: PublishStage[],
  logs: PublishLogEntry[]
): string {
  const timestamp = new Date().toISOString();
  const failedStage = stages.find(s => s.status === "error");
  
  const logSection = logs.length > 0 
    ? `### Execution Logs\n\`\`\`\n${logs.map(l => `[${l.timestamp}] [${l.level.toUpperCase()}] [${l.step}] ${l.message}`).join('\n')}\n\`\`\`\n`
    : "";
  
  return `## Publish Error Report

**App:** WP Plugin Publish
**Timestamp:** ${timestamp}

### Context
- **Plugin:** ${pluginName} (ID: ${pluginId})
- **Site:** ${siteName} (ID: ${siteId})
- **Failed Stage:** ${failedStage?.label || "Unknown"}

### Error Message
\`\`\`
${errorMessage}
\`\`\`

### Stage Status
${stages.map(s => `- ${s.label}: ${s.status}${s.message ? ` - ${s.message}` : ""}`).join("\n")}

${logSection}
---
*Generated by WP Plugin Publish Error Reporter*`;
}

const STAGE_LABELS: Record<string, string> = {
  backup: "Creating Backup",
  package: "Packaging Files",
  upload: "Uploading to Site",
  activate: "Activating Plugin",
  cleanup: "Cleaning Up",
  verify: "Verifying Deployment",
};

const DEFAULT_STAGES: PublishStage[] = [
  { name: "backup", label: "Creating Backup", status: "pending" },
  { name: "package", label: "Packaging Files", status: "pending" },
  { name: "upload", label: "Uploading to Site", status: "pending" },
  { name: "activate", label: "Activating Plugin", status: "pending" },
];

export function PublishProgressDialog({
  open,
  onOpenChange,
  pluginName,
  siteName,
  siteUrl,
  pluginId,
  siteId,
  onComplete,
}: PublishProgressDialogProps) {
  const { captureError, openErrorModal } = useErrorStore();
  const [stages, setStages] = useState<PublishStage[]>(DEFAULT_STAGES);
  const [overallProgress, setOverallProgress] = useState(0);
  const [isComplete, setIsComplete] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [filesUpdated, setFilesUpdated] = useState<number | null>(null);
  const [backendStackTrace, setBackendStackTrace] = useState<string | null>(null);
  
  // Live logs
  const [logs, setLogs] = useState<PublishLogEntry[]>([]);
  const [showLogs, setShowLogs] = useState(true);
  const logsEndRef = useRef<HTMLDivElement>(null);
  
  // Upload mode setting
  const [useFileByFile, setUseFileByFile] = useState(() => {
    const saved = localStorage.getItem("settings");
    if (saved) {
      try {
        const settings = JSON.parse(saved);
        return settings.uploadMode === "file-by-file";
      } catch { /* ignore */ }
    }
    return true; // default to file-by-file
  });

  // Auto-scroll logs
  useEffect(() => {
    if (showLogs && logsEndRef.current) {
      logsEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [logs, showLogs]);

  // Reset state when dialog opens
  useEffect(() => {
    if (open) {
      setStages(DEFAULT_STAGES.map(s => ({ ...s, status: "pending" })));
      setOverallProgress(0);
      setIsComplete(false);
      setIsSuccess(false);
      setErrorMessage(null);
      setFilesUpdated(null);
      setBackendStackTrace(null);
      setLogs([]);
    }
  }, [open]);

  // Listen for WebSocket events
  useEffect(() => {
    if (!open) return;

    // Handle publish started
    const unsubProgress = wsClient.on(WS_EVENTS.PUBLISH_STARTED, (data: unknown) => {
      const payload = data as { pluginId: number; siteId: number };
      if (payload.pluginId === pluginId && payload.siteId === siteId) {
        setStages(prev => prev.map(s => 
          s.name === "backup" ? { ...s, status: "running" } : s
        ));
        // Add initial log
        setLogs(prev => [...prev, {
          timestamp: new Date().toISOString(),
          level: 'info',
          step: 'init',
          message: `Starting publish for ${pluginName} to ${siteName}`,
        }]);
      }
    });

    const unsubStageProgress = wsClient.on("publish_progress", (data: unknown) => {
      const payload = data as PublishProgressPayload;
      if (payload.pluginId === pluginId && payload.siteId === siteId) {
        const stageName = payload.stage;
        
        // Add log entry if provided
        if (payload.log) {
          setLogs(prev => [...prev, payload.log!]);
        } else if (payload.message) {
          // Create log from progress message
          setLogs(prev => [...prev, {
            timestamp: new Date().toISOString(),
            level: 'info',
            step: stageName,
            message: payload.message,
          }]);
        }
        
        setStages(prev => prev.map(s => {
          if (s.name === stageName) {
            let mappedStatus: PublishStage["status"] = "running";
            if (payload.status === "success" || payload.status === "completed") mappedStatus = "success";
            else if (payload.status === "error" || payload.status === "failed") mappedStatus = "error";
            
            return {
              ...s,
              status: mappedStatus,
              message: payload.message,
            };
          }
          if (s.status === "running" && s.name !== stageName) {
            return { ...s, status: "success" };
          }
          return s;
        }));
        setOverallProgress(payload.progress);
      }
    });

    // Listen for log events specifically
    const unsubLog = wsClient.on(WS_EVENTS.LOG, (data: unknown) => {
      const payload = data as { pluginId?: number; siteId?: number; log?: PublishLogEntry };
      if (payload.pluginId === pluginId && payload.siteId === siteId && payload.log) {
        setLogs(prev => [...prev, payload.log!]);
      }
    });

    const unsubComplete = wsClient.on(WS_EVENTS.PUBLISH_COMPLETE, (data: unknown) => {
      const payload = data as PublishCompletePayload & { status?: string; message?: string };
      if (payload.pluginId === pluginId && payload.siteId === siteId) {
        const wasSuccessful = payload.success ?? (payload.status === "completed" || payload.status === "success");
        
        setIsComplete(true);
        setIsSuccess(wasSuccessful);
        setFilesUpdated(payload.filesUpdated ?? null);
        setOverallProgress(100);
        
        if (payload.error || (payload.message && !wasSuccessful)) {
          setErrorMessage(payload.error || payload.message || "Unknown error");
        }
        
        if (payload.backendStackTrace) {
          setBackendStackTrace(payload.backendStackTrace);
        }
        
        // Append any final logs
        if (payload.logs?.length) {
          setLogs(prev => [...prev, ...payload.logs!]);
        }
        
        // Add completion log
        setLogs(prev => [...prev, {
          timestamp: new Date().toISOString(),
          level: wasSuccessful ? 'info' : 'error',
          step: 'complete',
          message: wasSuccessful 
            ? `Publish completed successfully (${payload.filesUpdated || 0} files updated)`
            : `Publish failed: ${payload.error || payload.message || 'Unknown error'}`,
        }]);
        
        if (payload.stages) {
          setStages(payload.stages);
        } else {
          setStages(prev => prev.map(s => ({
            ...s,
            status: wasSuccessful ? "success" : (s.status === "running" ? "error" : s.status)
          })));
        }

        onComplete?.(wasSuccessful);
      }
    });

    return () => {
      unsubProgress();
      unsubStageProgress();
      unsubLog();
      unsubComplete();
    };
  }, [open, pluginId, siteId, pluginName, siteName, onComplete]);

  const getStageIcon = (stage: PublishStage) => {
    switch (stage.status) {
      case "success":
        return <Check className="h-4 w-4 text-primary" />;
      case "error":
        return <X className="h-4 w-4 text-destructive" />;
      case "running":
        return <div className="h-4 w-4 border-2 border-primary border-t-transparent rounded-full animate-spin" />;
      default:
        return <div className="h-4 w-4 rounded-full border-2 border-muted-foreground/30" />;
    }
  };

  const activeStageCount = stages.filter(s => s.status === "success" || s.status === "running").length;
  const totalStages = stages.length;
  
  // Convert logs to BackendLogEntry format for error store
  const backendLogs: BackendLogEntry[] = logs.map(l => ({
    timestamp: l.timestamp,
    level: l.level,
    message: l.message,
    step: l.step,
    details: l.details,
  }));

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg max-h-[90vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Upload className="h-5 w-5 text-primary" />
            {isComplete ? (isSuccess ? "Publish Complete" : "Publish Failed") : "Publishing..."}
          </DialogTitle>
          <DialogDescription>
            Deploying <strong>{pluginName}</strong> to <strong>{siteName}</strong>
            {siteUrl && (
              <a 
                href={siteUrl} 
                target="_blank" 
                rel="noopener noreferrer"
                className="ml-2 text-primary hover:underline inline-flex items-center gap-1"
              >
                <ExternalLink className="h-3 w-3" />
                Open Site
              </a>
            )}
          </DialogDescription>
        </DialogHeader>

        <div className="flex-1 overflow-hidden space-y-4 py-4">
          {/* Settings toggle - only show before completion */}
          {!isComplete && (
            <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
              <div className="flex items-center gap-2">
                <Settings2 className="h-4 w-4 text-muted-foreground" />
                <Label htmlFor="upload-mode" className="text-sm">
                  Upload Mode
                </Label>
              </div>
              <div className="flex items-center gap-2">
                <span className={cn("text-xs", !useFileByFile && "text-primary font-medium")}>ZIP</span>
                <Switch
                  id="upload-mode"
                  checked={useFileByFile}
                  onCheckedChange={(checked) => {
                    setUseFileByFile(checked);
                    // Save to settings
                    const saved = localStorage.getItem("settings");
                    const settings = saved ? JSON.parse(saved) : {};
                    settings.uploadMode = checked ? "file-by-file" : "zip";
                    localStorage.setItem("settings", JSON.stringify(settings));
                    toast.success(`Upload mode: ${checked ? "File-by-file" : "ZIP"}`);
                  }}
                />
                <span className={cn("text-xs", useFileByFile && "text-primary font-medium")}>File-by-file</span>
              </div>
            </div>
          )}

          {/* Overall Progress */}
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span className="text-muted-foreground">
                Stage {Math.min(activeStageCount + 1, totalStages)} of {totalStages}
              </span>
              <span className="font-medium">{Math.round(overallProgress)}%</span>
            </div>
            <Progress value={overallProgress} className="h-2" />
          </div>

          {/* Stage List */}
          <div className="space-y-2">
            {stages.map((stage) => (
              <div
                key={stage.name}
                className={cn(
                  "flex items-center gap-3 p-3 rounded-lg border transition-colors",
                  stage.status === "running" && "border-primary bg-primary/5",
                  stage.status === "success" && "border-primary/30 bg-primary/5",
                  stage.status === "error" && "border-destructive bg-destructive/5",
                  stage.status === "pending" && "border-border opacity-60"
                )}
              >
                {getStageIcon(stage)}
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium">{stage.label}</p>
                  {stage.message && (
                    <p className="text-xs text-muted-foreground truncate">
                      {stage.message}
                    </p>
                  )}
                </div>
                {stage.status === "success" && (
                  <Badge variant="outline" className="text-xs text-primary border-primary/30">
                    Done
                  </Badge>
                )}
                {stage.status === "error" && (
                  <Badge variant="outline" className="text-xs text-destructive border-destructive/30">
                    Failed
                  </Badge>
                )}
              </div>
            ))}
          </div>

          {/* Live Logs Section */}
          <div className="border rounded-lg overflow-hidden">
            <button
              onClick={() => setShowLogs(!showLogs)}
              className="w-full flex items-center justify-between p-3 bg-muted/50 hover:bg-muted transition-colors"
            >
              <div className="flex items-center gap-2">
                <Terminal className="h-4 w-4 text-muted-foreground" />
                <span className="text-sm font-medium">Live Logs</span>
                <Badge variant="secondary" className="text-xs">{logs.length}</Badge>
              </div>
              <span className="text-xs text-muted-foreground">
                {showLogs ? "Hide" : "Show"}
              </span>
            </button>
            {showLogs && (
              <ScrollArea className="h-32 bg-background">
                <div className="p-2 space-y-1 text-xs font-mono">
                  {logs.length === 0 ? (
                    <p className="text-muted-foreground text-center py-4">Waiting for logs...</p>
                  ) : (
                    logs.map((log, idx) => (
                      <div 
                        key={idx}
                        className={cn(
                          "py-0.5 px-1 rounded",
                          log.level === 'error' && "text-destructive",
                          log.level === 'warn' && "text-warning",
                          log.level === 'info' && "text-foreground",
                          log.level === 'debug' && "text-muted-foreground"
                        )}
                      >
                        <span className="text-muted-foreground">[{new Date(log.timestamp).toLocaleTimeString()}]</span>
                        <span className="text-primary ml-1">[{log.step}]</span>
                        <span className="ml-1">{log.message}</span>
                      </div>
                    ))
                  )}
                  <div ref={logsEndRef} />
                </div>
              </ScrollArea>
            )}
          </div>

          {/* Success Message */}
          {isComplete && isSuccess && filesUpdated !== null && (
            <div className="rounded-lg border border-primary/30 bg-primary/5 p-4">
              <div className="flex items-center gap-2">
                <Check className="h-5 w-5 text-primary" />
                <span className="font-medium">
                  Successfully published {filesUpdated} files
                </span>
              </div>
              {siteUrl && (
                <a 
                  href={siteUrl} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="mt-2 inline-flex items-center gap-1 text-sm text-primary hover:underline"
                >
                  <ExternalLink className="h-3 w-3" />
                  Open {siteName}
                </a>
              )}
            </div>
          )}

          {/* Error Message with Copy and View Details */}
          {isComplete && !isSuccess && errorMessage && (
            <div className="rounded-lg border border-destructive/30 bg-destructive/5 p-4 space-y-3">
              <div className="flex items-start gap-2">
                <AlertCircle className="h-5 w-5 text-destructive mt-0.5 flex-shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="font-medium text-destructive">Publish Failed</p>
                  <p className="text-sm text-muted-foreground mt-1 break-words">{errorMessage}</p>
                </div>
              </div>
              
              {/* Action buttons for error */}
              <div className="flex gap-2 pt-2 border-t border-destructive/20">
                <Button
                  variant="outline"
                  size="sm"
                  className="text-xs"
                  onClick={() => {
                    const report = buildErrorReport(pluginName, siteName, pluginId, siteId, errorMessage, stages, logs);
                    navigator.clipboard.writeText(report);
                    toast.success("Error report copied to clipboard");
                  }}
                >
                  <Copy className="h-3 w-3 mr-1" />
                  Copy Error
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  className="text-xs text-destructive hover:text-destructive"
                  onClick={() => {
                    const failedStage = stages.find(s => s.status === "error");
                    const captured = captureError(
                      {
                        code: "E9001",
                        message: errorMessage,
                        details: `Failed during stage: ${failedStage?.label || "Unknown"}`,
                        timestamp: new Date().toISOString(),
                      },
                      {
                        endpoint: `/plugins/${pluginId}/sites/${siteId}/publish`,
                        method: "POST",
                        context: {
                          source: "PublishProgressDialog.onComplete",
                          triggerComponent: "PublishProgressDialog",
                          triggerAction: "publish_failed",
                          pluginId,
                          pluginName,
                          siteId,
                          siteName,
                          failedStage: failedStage?.name,
                          stageStatuses: stages.map(s => ({ name: s.name, status: s.status, message: s.message })),
                        },
                        backendLogs,
                        backendStackTrace: backendStackTrace || undefined,
                        siteUrl,
                      }
                    );
                    openErrorModal(captured);
                  }}
                >
                  <ExternalLink className="h-3 w-3 mr-1" />
                  View Full Details
                </Button>
              </div>
            </div>
          )}
        </div>

        <DialogFooter>
          <Button
            variant={isComplete ? "default" : "outline"}
            onClick={() => onOpenChange(false)}
          >
            {isComplete ? "Done" : "Close"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
