import { useState, useEffect } from "react";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { wsClient, WS_EVENTS } from "@/lib/ws";
import { Check, X, Upload, AlertCircle, ExternalLink, Copy, Settings2, ListChecks, Terminal, Activity, ArrowRight } from "lucide-react";
import { cn } from "@/lib/utils";
import { useErrorStore, BackendLogEntry } from "@/stores/errorStore";
import { toast } from "sonner";
import { LogViewer, LogEntry } from "@/components/shared/LogViewer";
import { ActivationDiagnostics } from "@/components/plugins/ActivationDiagnostics";
import { api } from "@/lib/api";
import { compareVersions } from "@/lib/versionUtils";

export interface PublishStage {
  name: string;
  label: string;
  status: "pending" | "running" | "success" | "error" | "skipped";
  message?: string;
  startedAt?: string;
  completedAt?: string;
}

// Re-use LogEntry from LogViewer
type PublishLogEntry = LogEntry;

interface PublishProgressPayload {
  publishId: string;
  pluginId: number;
  siteId: number;
  stage: string;
  progress: number;
  message: string;
  status: string;
  log?: PublishLogEntry;
}

interface PublishCompletePayload {
  publishId: string;
  pluginId: number;
  siteId: number;
  /** @deprecated Use isSuccess instead */
  success?: boolean;
  isSuccess?: boolean;
  filesUpdated?: number;
  error?: string;
  stages: PublishStage[];
  logs?: PublishLogEntry[];
  backendStackTrace?: string;
}

interface PublishProgressDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  pluginName: string;
  siteName: string;
  siteUrl?: string;
  pluginId: number;
  siteId: number;
  onComplete?: (success: boolean) => void;
}

// Build a copyable error report for the publish failure
function buildErrorReport(
  pluginName: string,
  siteName: string,
  pluginId: number,
  siteId: number,
  errorMessage: string,
  stages: PublishStage[],
  logs: PublishLogEntry[]
): string {
  const timestamp = new Date().toISOString();
  const failedStage = stages.find(s => s.status === "error");

  const logLines = logs.map((l) => {
    const base = `[${l.timestamp}] [${l.level.toUpperCase()}] [${l.step}] ${l.message}`;
    if (!l.details || Object.keys(l.details).length === 0) return base;
    try {
      return `${base}\n  details=${JSON.stringify(l.details)}`;
    } catch {
      return `${base}\n  details=[unserializable]`;
    }
  });

  const logSection = logs.length > 0
    ? `### Execution Logs\n\`\`\`\n${logLines.join("\n")}\n\`\`\`\n`
    : "";
  
  return `## Publish Error Report

**App:** WP Plugin Publish
**Timestamp:** ${timestamp}

### Context
- **Plugin:** ${pluginName} (ID: ${pluginId})
- **Site:** ${siteName} (ID: ${siteId})
- **Failed Stage:** ${failedStage?.label || "Unknown"}

### Error Message
\`\`\`
${errorMessage}
\`\`\`

### Stage Status
${stages.map(s => `- ${s.label}: ${s.status}${s.message ? ` - ${s.message}` : ""}`).join("\n")}

${logSection}
---
*Generated by WP Plugin Publish Error Reporter*`;
}

const STAGE_LABELS: Record<string, string> = {
  backup: "Creating Backup",
  package: "Packaging Files",
  upload: "Uploading to Site",
  activate: "Activating Plugin",
  cleanup: "Cleaning Up",
  verify: "Verifying Deployment",
  version_check: "Verifying Version",
};

const DEFAULT_STAGES: PublishStage[] = [
  { name: "backup", label: "Creating Backup", status: "pending" },
  { name: "package", label: "Packaging Files", status: "pending" },
  { name: "upload", label: "Uploading to Site", status: "pending" },
  { name: "activate", label: "Activating Plugin", status: "pending" },
  { name: "version_check", label: "Verifying Version", status: "pending" },
];

export function PublishProgressDialog({
  open,
  onOpenChange,
  pluginName,
  siteName,
  siteUrl,
  pluginId,
  siteId,
  onComplete,
}: PublishProgressDialogProps) {
  const { captureError, openErrorModal } = useErrorStore();
  const [stages, setStages] = useState<PublishStage[]>(DEFAULT_STAGES);
  const [overallProgress, setOverallProgress] = useState(0);
  const [isComplete, setIsComplete] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [filesUpdated, setFilesUpdated] = useState<number | null>(null);
  const [backendStackTrace, setBackendStackTrace] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<string>("progress");
  
  // Version info
  const [localVersion, setLocalVersion] = useState<string | null>(null);
  const [remoteVersion, setRemoteVersion] = useState<string | null>(null);
  
  // Live logs
  const [logs, setLogs] = useState<PublishLogEntry[]>([]);
  
  // Upload mode setting
  const [useFileByFile, setUseFileByFile] = useState(() => {
    const saved = localStorage.getItem("settings");
    if (saved) {
      try {
        const settings = JSON.parse(saved);
        return settings.uploadMode === "file-by-file";
      } catch { /* ignore */ }
    }
    return true; // default to file-by-file
  });

  // Keep ZIP files setting
  const [keepZipFiles, setKeepZipFiles] = useState(() => {
    try {
      const saved = localStorage.getItem("wppp_keep_zip_files");
      return saved === "true";
    } catch {
      return false;
    }
  });

  // Reset state when dialog opens & fetch version info immediately
  useEffect(() => {
    if (open) {
      setStages(DEFAULT_STAGES.map(s => ({ ...s, status: "pending" })));
      setOverallProgress(0);
      setIsComplete(false);
      setIsSuccess(false);
      setErrorMessage(null);
      setFilesUpdated(null);
      setBackendStackTrace(null);
      setLogs([]);
      setActiveTab("progress");
      setRemoteVersion(null);
      
      // Fetch version info — local version comes back instantly from backend cache,
      // remote version may take longer (network call to WP site)
      if (pluginId && siteId) {
        api.previewPublish(pluginId, siteId).then(response => {
          if (response.success && response.data) {
            setLocalVersion(response.data.localVersion || null);
            setRemoteVersion(response.data.remoteVersion || null);
          }
        }).catch(() => {});
      }
    }
  }, [open, pluginId, siteId]);

  // Listen for WebSocket events
  useEffect(() => {
    if (!open) return;

    // Handle publish started
    const unsubProgress = wsClient.on(WS_EVENTS.PUBLISH_STARTED, (data: unknown) => {
      const payload = data as { pluginId: number; siteId: number };
      if (payload.pluginId === pluginId && payload.siteId === siteId) {
        setStages(prev => prev.map(s => 
          s.name === "backup" ? { ...s, status: "running" } : s
        ));
        // Add initial log
        setLogs(prev => [...prev, {
          timestamp: new Date().toISOString(),
          level: 'info',
          step: 'init',
          message: `Starting publish for ${pluginName} to ${siteName}`,
        }]);
      }
    });

    const unsubStageProgress = wsClient.on("publish_progress", (data: unknown) => {
      const payload = data as PublishProgressPayload;
      if (payload.pluginId === pluginId && payload.siteId === siteId) {
        const stageName = payload.stage;
        
        // Add log entry if provided
        if (payload.log) {
          setLogs(prev => [...prev, payload.log!]);
        }
        
        setStages(prev => prev.map(s => {
          if (s.name === stageName) {
            let mappedStatus: PublishStage["status"] = "running";
            if (payload.status === "success" || payload.status === "completed") mappedStatus = "success";
            else if (payload.status === "error" || payload.status === "failed") mappedStatus = "error";
            
            return {
              ...s,
              status: mappedStatus,
              message: payload.message,
            };
          }
          if (s.status === "running" && s.name !== stageName) {
            return { ...s, status: "success" };
          }
          return s;
        }));
        setOverallProgress(payload.progress);
      }
    });

    // Listen for log events specifically
    const unsubLog = wsClient.on(WS_EVENTS.LOG, (data: unknown) => {
      const payload = data as { pluginId?: number; siteId?: number; operationType?: string; log?: PublishLogEntry };
      if (payload.operationType === "publish" && payload.pluginId === pluginId && payload.siteId === siteId && payload.log) {
        setLogs(prev => [...prev, payload.log!]);
      }
    });

    const unsubComplete = wsClient.on(WS_EVENTS.PUBLISH_COMPLETE, (data: unknown) => {
      const payload = data as PublishCompletePayload & { status?: string; message?: string };
      if (payload.pluginId === pluginId && payload.siteId === siteId) {
        const wasSuccessful = payload.isSuccess ?? payload.success ?? (payload.status === "completed" || payload.status === "success");
        
        setIsComplete(true);
        setIsSuccess(wasSuccessful);
        setFilesUpdated(payload.filesUpdated ?? null);
        
        // Force progress to 100% on completion — never leave it partial
        setOverallProgress(100);
        
        if (payload.error || (payload.message && !wasSuccessful)) {
          setErrorMessage(payload.error || payload.message || "Unknown error");
        }
        
        if (payload.backendStackTrace) {
          setBackendStackTrace(payload.backendStackTrace);
        }
        
        // Append any final logs
        if (payload.logs?.length) {
          setLogs(prev => [...prev, ...payload.logs!]);
        }
        
        // Add completion log
        setLogs(prev => [...prev, {
          timestamp: new Date().toISOString(),
          level: wasSuccessful ? 'info' : 'error',
          step: 'complete',
          message: wasSuccessful 
            ? `Publish completed successfully (${payload.filesUpdated || 0} files updated)`
            : `Publish failed: ${payload.error || payload.message || 'Unknown error'}`,
        }]);
        
        // FORCE all stages (except version_check) to correct final state
        if (payload.stages) {
          setStages(payload.stages.map(s => ({
            ...s,
            // Keep version_check pending — it runs after completion
            status: s.name === "version_check" ? "pending" : (wasSuccessful && s.status !== "skipped" ? "success" : s.status),
          })));
        } else {
          setStages(prev => prev.map(s => ({
            ...s,
            status: s.name === "version_check" ? "pending" : (wasSuccessful ? "success" : (s.status === "running" || s.status === "pending" ? "error" : s.status))
          })));
        }

        // Post-publish version verification (like PS script does)
        if (wasSuccessful && pluginId && siteId) {
          setStages(prev => prev.map(s => 
            s.name === "version_check" ? { ...s, status: "running", message: "Checking remote version..." } : s
          ));
          api.previewPublish(pluginId, siteId).then(response => {
            if (response.success && response.data) {
              const newRemote = response.data.remoteVersion;
              const local = response.data.localVersion;
              setRemoteVersion(newRemote || null);
              setLocalVersion(local || null);
              
              const versionMatch = newRemote && local && newRemote === local;
              setStages(prev => prev.map(s => 
                s.name === "version_check" ? { 
                  ...s, 
                  status: versionMatch ? "success" : "error",
                  message: versionMatch 
                    ? `Verified: v${newRemote} deployed` 
                    : `Version mismatch: remote=${newRemote || 'unknown'}, expected=${local}`
                } : s
              ));
              if (versionMatch) {
                setLogs(prev => [...prev, {
                  timestamp: new Date().toISOString(),
                  level: 'info',
                  step: 'version_check',
                  message: `✓ Version verified: remote is now v${newRemote}`,
                }]);
              } else {
                setLogs(prev => [...prev, {
                  timestamp: new Date().toISOString(),
                  level: 'warn',
                  step: 'version_check',
                  message: `⚠ Version mismatch: remote=${newRemote || 'unknown'}, expected=${local}. OPcache may need flushing.`,
                }]);
              }
            }
          }).catch(() => {
            setStages(prev => prev.map(s => 
              s.name === "version_check" ? { ...s, status: "skipped", message: "Could not verify" } : s
            ));
          });
        }

        onComplete?.(wasSuccessful);
      }
    });

    return () => {
      unsubProgress();
      unsubStageProgress();
      unsubLog();
      unsubComplete();
    };
  }, [open, pluginId, siteId, pluginName, siteName, onComplete]);

  const getStageIcon = (stage: PublishStage) => {
    switch (stage.status) {
      case "success":
        return <Check className="h-4 w-4 text-primary" />;
      case "error":
        return <X className="h-4 w-4 text-destructive" />;
      case "running":
        return <div className="h-4 w-4 border-2 border-primary border-t-transparent rounded-full animate-spin" />;
      default:
        return <div className="h-4 w-4 rounded-full border-2 border-muted-foreground/30" />;
    }
  };

  const activeStageCount = stages.filter(s => s.status === "success" || s.status === "running").length;
  const totalStages = stages.length;
  
  // Convert logs to BackendLogEntry format for error store
  const backendLogs: BackendLogEntry[] = logs.map(l => ({
    timestamp: l.timestamp,
    level: l.level,
    message: l.message,
    step: l.step,
    details: l.details,
  }));

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-2xl lg:max-w-3xl max-h-[90vh] flex flex-col overflow-hidden">
        <DialogHeader className="flex-shrink-0">
          <DialogTitle className="flex items-center gap-2">
            <Upload className="h-5 w-5 text-primary" />
            {isComplete ? (isSuccess ? "Publish Complete" : "Publish Failed") : "Publishing..."}
          </DialogTitle>
          <DialogDescription className="flex items-center gap-2 flex-wrap min-h-0">
            <span className="truncate">Deploying <strong>{pluginName}</strong> to <strong className="truncate max-w-[200px] inline-block align-bottom">{siteName}</strong></span>
            {localVersion ? (
              <span className="inline-flex items-center gap-1.5 text-xs flex-shrink-0">
                {/* Local version (NEW) — highlighted */}
                <Badge className="text-[10px] font-mono h-5 px-1.5 bg-primary text-primary-foreground font-bold">
                  v{localVersion}
                </Badge>
                <ArrowRight className="h-3 w-3 text-muted-foreground flex-shrink-0" />
                {/* Remote version (OLD) — subtle */}
                {remoteVersion ? (
                  <Badge variant="outline" className="text-[10px] font-mono h-5 px-1.5 text-muted-foreground">
                    v{remoteVersion}
                  </Badge>
                ) : (
                  <Badge variant="outline" className="text-[10px] italic text-muted-foreground h-5 px-1.5">
                    new install
                  </Badge>
                )}
              </span>
            ) : remoteVersion ? (
              <span className="inline-flex items-center gap-1.5 text-xs flex-shrink-0">
                <Badge variant="outline" className="text-[10px] font-mono h-5 px-1.5 text-muted-foreground">
                  v{remoteVersion}
                </Badge>
              </span>
            ) : (
              <span className="inline-flex items-center gap-1 text-xs text-muted-foreground flex-shrink-0">
                <div className="h-3 w-3 border border-muted-foreground/40 border-t-transparent rounded-full animate-spin" />
                loading...
              </span>
            )}
            {siteUrl && (
              <a 
                href={siteUrl} 
                target="_blank" 
                rel="noopener noreferrer"
                className="text-primary hover:underline inline-flex items-center gap-1 flex-shrink-0 ml-auto"
              >
                <ExternalLink className="h-3 w-3" />
                Open Site
              </a>
            )}
          </DialogDescription>
        </DialogHeader>

        {/* Tabbed content for better screen fit */}
        <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col overflow-hidden">
          <TabsList className="w-full flex flex-shrink-0">
            <TabsTrigger value="progress" className="flex-1 gap-1 text-xs sm:text-sm">
              <ListChecks className="h-3 w-3" />
              Progress
            </TabsTrigger>
            <TabsTrigger value="logs" className="flex-1 gap-1 text-xs sm:text-sm">
              <Terminal className="h-3 w-3" />
              Logs
              <Badge variant="secondary" className="ml-1 text-[10px]">{logs.length}</Badge>
            </TabsTrigger>
            <TabsTrigger value="diagnostics" className="flex-1 gap-1 text-xs sm:text-sm">
              <Activity className="h-3 w-3" />
              Diag
            </TabsTrigger>
            <TabsTrigger value="settings" className="flex-1 gap-1 text-xs sm:text-sm" disabled={isComplete}>
              <Settings2 className="h-3 w-3" />
              Settings
            </TabsTrigger>
          </TabsList>

          {/* Progress Tab */}
          <TabsContent value="progress" className="flex-1 overflow-hidden mt-4">
            <ScrollArea className="h-full pr-4">
              <div className="space-y-4">
                {/* Overall Progress */}
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">
                      Stage {Math.min(activeStageCount + 1, totalStages)} of {totalStages}
                    </span>
                    <span className="font-medium">{Math.round(overallProgress)}%</span>
                  </div>
                  <Progress value={overallProgress} className="h-2" />
                </div>

                {/* Stage List */}
                <div className="space-y-2">
                  {stages.map((stage) => (
                    <div
                      key={stage.name}
                      className={cn(
                        "flex items-center gap-3 p-3 rounded-lg border transition-colors",
                        stage.status === "running" && "border-primary bg-primary/5",
                        stage.status === "success" && "border-primary/30 bg-primary/5",
                        stage.status === "error" && "border-destructive bg-destructive/5",
                        stage.status === "pending" && "border-border opacity-60"
                      )}
                    >
                      {getStageIcon(stage)}
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <p className="text-sm font-medium">{stage.label}</p>
                          {/* Show local version on deploy stages, remote on version_check */}
                          {stage.name !== "version_check" && localVersion && stage.status !== "pending" && (
                            <Badge className="text-[10px] font-mono h-4 px-1.5 bg-primary/80 text-primary-foreground">
                              v{localVersion}
                            </Badge>
                          )}
                          {stage.name === "version_check" && remoteVersion && stage.status !== "pending" && (
                            <Badge variant="outline" className="text-[10px] font-mono h-4 px-1.5 border-accent text-accent-foreground">
                              v{remoteVersion}
                              <span className="ml-1 text-muted-foreground font-normal">server</span>
                            </Badge>
                          )}
                        </div>
                        {stage.message && (
                          <p className="text-xs text-muted-foreground truncate">
                            {stage.message}
                          </p>
                        )}
                      </div>
                      {stage.status === "success" && (
                        <Badge variant="outline" className="text-xs text-primary border-primary/30 flex-shrink-0">
                          Done
                        </Badge>
                      )}
                      {stage.status === "error" && (
                        <Badge variant="outline" className="text-xs text-destructive border-destructive/30 flex-shrink-0">
                          Failed
                        </Badge>
                      )}
                    </div>
                  ))}
                </div>

                {/* Success Message */}
                {isComplete && isSuccess && filesUpdated !== null && (
                  <div className="rounded-lg border border-primary/30 bg-primary/5 p-4">
                    <div className="flex items-center gap-2">
                      <Check className="h-5 w-5 text-primary" />
                      <span className="font-medium">
                        Successfully published {filesUpdated} files
                      </span>
                    </div>
                    {siteUrl && (
                      <a 
                        href={siteUrl} 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="mt-2 inline-flex items-center gap-1 text-sm text-primary hover:underline"
                      >
                        <ExternalLink className="h-3 w-3" />
                        Open {siteName}
                      </a>
                    )}
                  </div>
                )}

                {/* Error Message */}
                {isComplete && !isSuccess && errorMessage && (
                  <div className="rounded-lg border border-destructive/30 bg-destructive/5 p-4 space-y-3">
                    <div className="flex items-start gap-2">
                      <AlertCircle className="h-5 w-5 text-destructive mt-0.5 flex-shrink-0" />
                      <div className="flex-1 min-w-0">
                        <p className="font-medium text-destructive">Publish Failed</p>
                        <p className="text-sm text-muted-foreground mt-1 break-words">{errorMessage}</p>
                      </div>
                    </div>
                    
                    <div className="flex gap-2 pt-2 border-t border-destructive/20">
                      <Button
                        variant="outline"
                        size="sm"
                        className="text-xs"
                        onClick={() => {
                          const report = buildErrorReport(pluginName, siteName, pluginId, siteId, errorMessage, stages, logs);
                          navigator.clipboard.writeText(report);
                          toast.success("Error report copied to clipboard");
                        }}
                      >
                        <Copy className="h-3 w-3 mr-1" />
                        Copy Error
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        className="text-xs text-destructive hover:text-destructive"
                        onClick={() => {
                          const failedStage = stages.find(s => s.status === "error");
                          const captured = captureError(
                            {
                              code: "E9001",
                              message: errorMessage,
                              details: `Failed during stage: ${failedStage?.label || "Unknown"}`,
                              timestamp: new Date().toISOString(),
                            },
                            {
                              endpoint: `/plugins/${pluginId}/sites/${siteId}/publish`,
                              method: "POST",
                              context: {
                                source: "PublishProgressDialog.onComplete",
                                triggerComponent: "PublishProgressDialog",
                                triggerAction: "publish_failed",
                                pluginId,
                                pluginName,
                                siteId,
                                siteName,
                                failedStage: failedStage?.name,
                                stageStatuses: stages.map(s => ({ name: s.name, status: s.status, message: s.message })),
                                backendLogFiles: {
                                  log: "data/errors/log.txt",
                                  errorLog: "data/errors/error.log.txt",
                                },
                              },
                              backendLogs,
                              backendStackTrace: backendStackTrace || undefined,
                              siteUrl,
                            }
                          );
                          openErrorModal(captured);
                        }}
                      >
                        <ExternalLink className="h-3 w-3 mr-1" />
                        View Details
                      </Button>
                    </div>
                  </div>
                )}
              </div>
            </ScrollArea>
          </TabsContent>

          {/* Logs Tab - Filter verbose file-listing logs by default */}
          <TabsContent value="logs" className="flex-1 overflow-hidden mt-4">
            <LogViewer
              logs={logs.filter(l => {
                // Hide verbose file-listing messages (e.g., "Adding file X", "Compressing file Y")
                const msg = l.message.toLowerCase();
                if (l.step === 'package' && (msg.includes('adding file') || msg.includes('compressing') || msg.includes('included in zip'))) return false;
                if (l.step === 'file_list' || l.step === 'zip_contents') return false;
                return true;
              })}
              title="Execution Logs"
              height="h-[300px]"
              showToggle={false}
              emptyMessage="Waiting for publish to start..."
              className="h-full"
            />
          </TabsContent>

          {/* Diagnostics Tab */}
          <TabsContent value="diagnostics" className="flex-1 overflow-hidden mt-4">
            <ActivationDiagnostics logs={logs} className="h-full" />
          </TabsContent>

          {/* Settings Tab */}
          <TabsContent value="settings" className="flex-1 overflow-hidden mt-4">
            <div className="space-y-4">
              <div className="flex items-center justify-between p-4 bg-muted/50 rounded-lg">
                <div>
                  <Label htmlFor="upload-mode" className="text-sm font-medium">
                    Upload Mode
                  </Label>
                  <p className="text-xs text-muted-foreground mt-1">
                    ZIP uploads the entire plugin as one file. File-by-file uploads changed files individually.
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <span className={cn("text-xs", !useFileByFile && "text-primary font-medium")}>ZIP</span>
                  <Switch
                    id="upload-mode"
                    checked={useFileByFile}
                    onCheckedChange={(checked) => {
                      setUseFileByFile(checked);
                      const saved = localStorage.getItem("settings");
                      const settings = saved ? JSON.parse(saved) : {};
                      settings.uploadMode = checked ? "file-by-file" : "zip";
                      localStorage.setItem("settings", JSON.stringify(settings));
                      toast.success(`Upload mode: ${checked ? "File-by-file" : "ZIP"}`);
                    }}
                  />
                  <span className={cn("text-xs", useFileByFile && "text-primary font-medium")}>File-by-file</span>
                </div>
              </div>

              <div className="flex items-center justify-between p-4 bg-muted/50 rounded-lg">
                <div>
                  <Label htmlFor="keep-zip" className="text-sm font-medium">
                    Keep ZIP Files
                  </Label>
                  <p className="text-xs text-muted-foreground mt-1">
                    Preserve ZIP files in temp folder after publish (for debugging).
                  </p>
                </div>
                <Switch
                  id="keep-zip"
                  checked={keepZipFiles}
                  onCheckedChange={(checked) => {
                    setKeepZipFiles(checked);
                    localStorage.setItem("wppp_keep_zip_files", String(checked));
                    toast.success(`Keep ZIP files: ${checked ? "enabled" : "disabled"}`);
                  }}
                />
              </div>
            </div>
          </TabsContent>
        </Tabs>

        <DialogFooter className="flex-shrink-0 pt-4 border-t">
          <Button
            variant={isComplete ? "default" : "outline"}
            onClick={() => onOpenChange(false)}
          >
            {isComplete ? "Done" : "Close"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
